### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by trvinh** [DessimozLab/pyomadb#2]
Dear omadb developers,

I am trying to install *omadb* from pypi, but somehow it didn't work (I have python 3.7.8). 
```
$ pip install omadb
Collecting omadb
  Using cached omadb-2.1.0-py3-none-any.whl (27 kB)
Collecting pandas
  Downloading pandas-1.1.2-cp37-cp37m-manylinux1_x86_64.whl (10.5 MB)
     |████████████████████████████████| 10.5 MB 13.7 MB/s 
Collecting requests-cache
  Using cached requests_cache-0.5.2-py2.py3-none-any.whl (22 kB)
Collecting property-manager
  Using cached property_manager-3.0-py2.py3-none-any.whl (23 kB)
ERROR: Could not find a version that satisfies the requirement pprint (from omadb) (from versions: none)
ERROR: No matching distribution found for pprint (from omadb)
```
Can you please check that? Many thanks!
Best,
Vinh

**Comment by trvinh** [comment]
I just want to notice, installing from download source file (https://files.pythonhosted.org/packages/e3/57/75b6f0bd65944a069cccdbebd53b51f7fce8057b13098f755617cbd9e3fb/omadb-2.1.0.tar.gz) also not works (it has the same error message).

**Comment by alex-wave** [comment]
Hi Vinh,

Thank you for bringing this to our attention. I think we erroneously included `pprint` into our requirements list here, as it's a standard library module. This must have slipped past us, as it seems to install fine on my system and reports the `pprint`  requirement as already satisfied.

Nevertheless, I have now removed it from the requirements and updated the package on PyPI. Please go ahead and install version 2.1.1.

Thanks once again and please let us know if this doesn't work for you.

Best wishes,
Alex

**Comment by trvinh** [comment]
Hi Alex,
it works now! Thanks for the quick fix :)
Best,
Vinh
