### ISSUE TITLE
properly releasing resources (filehandles)

### ISSUE THREAD

**Issue by alpae** [DessimozLab/pyomadb#3]
Seems like omadb client does not properly release resources (https://github.com/DessimozLab/OMArk/issues/25) 

putting the client as a module variable does not help, so it seems that we should use requests session to recycle the connections. (by default, omadb does not use the `CachedSession`.

**Comment by alex-wave** [comment]
This should be fixed in the new release v2.2.4, where we now use `Session` / `CachedSession` dependent on the setting `persistent_cached`.

If this is still an issue, I can investigate further.
